---
title: 'NOAA Plot Replication'
author: 'Created by: Jill E. Thomley'
date: 'Updated: `r format(Sys.time(), "%A, %B %d, %Y @ %X")`'
output: html_document
---

<hr> 

```{r, message=FALSE, echo=FALSE}
# Read in the datasets and load any necessary packages here
# Suppress the code and any messages / warnings it produces

library(dplyr)    # needed for cool data manipulation, like filter and mutate
library(ggplot2)  # needed for cool data visualization
library(ggthemes) # needed for theme_base()

ANNUAL  <- read.csv("CO2annualM.csv")
MONTHLY <- read.csv("CO2monthlyM.csv")
WEEKLY  <- read.csv("CO2weeklyM.csv")
GROWTH  <- read.csv("CO2growthM.csv")
```

```{r, echo=FALSE}
NOAATHEME <- theme_base(base_size = 15) +
             theme(axis.ticks.length = unit(-0.15, "cm"),
                   axis.text.x = element_text(margin = unit(c(0.4, 0.4, 0.4, 0.4), "cm")), 
                   axis.text.y = element_text(margin = unit(c(0.4, 0.4, 0.4, 0.4), "cm")),
                   plot.title = element_text(hjust = 0.5, margin = unit(c(0, 0, -0.4, 0), "cm")),
                   plot.background=element_blank())
```

* Replicate the content of the graph shown on [this page](https://www.esrl.noaa.gov/gmd/ccgg/trends/full.html).

```{r, echo=FALSE}
ggplot(MONTHLY) +
  geom_line(aes(x= decimaldate, y = interpolated), col = "red") +
  geom_line(aes(x= decimaldate, y = trend), col="black") +
  ggtitle(expression("Atmospheric CO"[2]*" at Mauna Loa Observatory")) +
  scale_x_continuous(breaks = seq(1960, 2020, 5), 
                     labels = c("1960", "", 
                                "1970", "", 
                                "1980", "", 
                                "1990", "", 
                                "2000", "",
                                "2010", "", 
                                "2020"),
                     limits = c(min(MONTHLY$year), 2020),
                     sec.axis = dup_axis(labels = NULL, name ="")) +  
  scale_y_continuous(breaks = seq(320, 410, 10), 
                     labels = c("320", "",
                                "340", "",
                                "360", "",
                                "380", "",
                                "400", ""),
                     sec.axis = dup_axis(labels = NULL, name ="")) +
  ylab("PARTS PER MILLION") +
  xlab("YEAR") +
  NOAATHEME
```

* Replicate the content of the graph shown on [this page](https://www.esrl.noaa.gov/gmd/ccgg/trends/index.html).

```{r, echo=FALSE}
MONTHLY2014 <- MONTHLY %>% filter(year >= 2014)

ggplot(MONTHLY2014) +
  geom_line(aes(x= decimaldate, y = interpolated), col = "red", linetype = 5) +
  geom_point(aes(x= decimaldate, y = interpolated), col = "red", shape=18) +
  geom_line(aes(x= decimaldate, y = trend), col="black") +
  geom_point(aes(x= decimaldate, y = trend), col = "black", shape=15) +
  scale_x_continuous(breaks = seq(2014, 2019, .25), 
                     labels = c("2014", rep("", 3), 
                                "2015", rep("", 3), 
                                "2016", rep("", 3),
                                "2017", rep("", 3),
                                "2018", rep("", 3),
                                "2019"),
                     limits = c(2014, 2019),
                     sec.axis = dup_axis(labels = NULL, name ="")) +
  scale_y_continuous(breaks = 395:415, 
                     labels = c("395", rep("", 4),
                                "400", rep("", 4),
                                "405", rep("", 4),
                                "410", rep("", 4),
                                "415"),
                     limits = c(395, 415),
                     sec.axis = dup_axis(labels = NULL, name ="")) +
  ggtitle(expression("RECENT MONTHLY MEAN CO"[2]*" AT MAUNA LOA")) +
  ylab("PARTS PER MILLION") +
  xlab("YEAR") +
  NOAATHEME

# Note: expand = c(0, 0) will get rid of the exta padding at the ends
# of the x-axis, but the tick marks and axis lines will overlap oddly 
```