---
title: "STT 3530 Data Science I<br>Course Schedule for Spring 2019"
author: "Instructor: Jill E. Thomley (thomleyje@appstate.edu)"
date: 'Updated: `r format(Sys.time(), "%A, %B %d, %Y @ %X")`'
output: 
  html_document: 
    toc: true
    toc_depth: 3
    toc_float: true
    highlight: textmate
    theme: cosmo
    css: "../css/style.css"
    keep_md: yes
---

***

```{block, WIP, type='rmdimportant'}
* **This schedule is a work in progress. Check often for updates!**
```

```{block, introtext, type='rmdnote'}
* We will be using free digital textbooks/resources in this course.
    + [GitHub](https://github.com/)
    + [DataCamp](https://www.datacamp.com/)
    + [_Modern Dive_](https://moderndive.com/)
    + [_R for Data Science_](https://r4ds.had.co.nz/)
    + Additional items listed below
* Please bring a notebook and pencil/pen to every class. 
* All of the required software for this course is provided.
* Be prepared to actively participate and collaborate.
* Refer to the [Course Syllabus](../Syllabus/SyllabusS2019.html) for additional details.
```

```{block, introoptional, type='rmdoptional'}
Optionally, you may wish to install [Git](http://git-scm.com/downloads), [R](http://cran.r-project.org), [RStudio](http://www.rstudio.com/products/rstudio/download/), [zotero](https://www.zotero.org), and  [$LaTeX$](http://www.ctan.org/starter) on your personal computer. If you do, follow Jenny Bryan's excellent advice for [installing R and RStudio](http://stat545-ubc.github.io/block000_r-rstudio-install.html) and [installing Git](http://stat545-ubc.github.io/git01_git-install.html).  Jenny's advice is also in chapters 6 and 7 of _[Happy Git and GitHub for the useR](http://happygitwithr.com/)_.  Note that [Git](http://git-scm.com/downloads), [R](http://cran.r-project.org), [RStudio](http://www.rstudio.com/products/rstudio/download/), and [$LaTeX$](http://www.ctan.org/starter) are all installed on the [ASU RStudio server](https://mathr.math.appstate.edu/) and you can access these resources using any web browser.

Watch the following videos as appropriate:

* [Install R on Mac (2 min)](https://www.youtube.com/watch?v=lJxVRgiX-ik)    
* [Install R for Windows (3 min)](https://www.youtube.com/watch?v=LII6of-5Odw)    
* [Install R and RStudio on Windows (5 min)](https://www.youtube.com/watch?v=eD07NznguA4)    
```

```{block, duedates, type='rmdimportant'}
* **All assignments are due Thursday @ 11pm of the week in which they appear.** 
* **Check AsULearn for project/homework assignment instructions and grades.**
```


***
### Course Overview

Class time in this course will be a mix of lecture and hands-on activities. Data science 1 is an introductory course with no statistics or programming prerequisites. Students come into the course with a broad mix of skills. This means that the most effective mode of instruction tends to be a semi-flipped classroom approach where some primary instruction occurs outside class, in this case largely in the form of Datacamp assignments. Students can work on DataCamp modules at their own pace in an iterative fashion. This frees up class time to spend on work where students can give and receive help from peers and the instructor. Do not treat this instructional mode as an invitation to skip class! Your classmates are one of your greatest resources.

**Abbreviations**

DC = _DataCamp_  
MD = _Modern Dive_  
RDS = _R for Data Science_  
HW = homework


#### Before Week 04


* Chapters 1, 8, and 10-13 of Jenny Bryan's [_Happy Git and GitHub for the useR_](http://happygitwithr.com/)
* Chapter "[Git and GitHub](http://r-pkgs.had.co.nz/git.html)" of Hadley Wickham's [_R Packages_](http://r-pkgs.had.co.nz/)


***
### Week 07 (FEB 26, 28)

#### Assignments Due

* Project 1 writeup
* Reflection #07

#### In-Class Activities

* Publishing in RPubs
* Work on Project 1 

#### Before Week 08

* RDS [Section 26. Introduction](http://r4ds.had.co.nz/communicate-intro.html)
* RDS [Section 27. R Markdown](http://r4ds.had.co.nz/r-#### MARkdown.html)
* RDS [Section 28. Graphics for Communication](http://r4ds.had.co.nz/graphics-for-communication.html)
* Stat545 ["Using Colors in R"](http://stat545.com/block018_colors.html)
* Stat545 ["Multiple Plots on a Page"](http://stat545.com/block020_multiple-plots-on-a-page.html)

```{block, week07note, type='rmdnote'}
* TBA NOTE
```

```{block, week07important, type='rmdimportant'}
* If you're not already caught up on your work, try to be on schedule by the time you get back!
```


***
### Spring Break


***
### Week 08 (MAR 12, 14)

#### Assignments Due

* DC [_Data Visualization with ggplot2 (Part 2)_](https://www.datacamp.com/courses/data-visualization-with-ggplot2-2) HW
* DC [_Data Visualization with ggplot2 (Part 3)_](https://www.datacamp.com/courses/data-visualization-with-ggplot2-part-3) HW
* Reflection #08

#### In-Class Activities

* Customizing plots in `ggplot2`
* Using and customizing themes
* Faceting and multiple plots
* Color brewer palettes

#### Before Week 09

* RDS [Section 9. Introduction](http://r4ds.had.co.nz/wrangle-intro.html)
* RDS [Section 10. Tibbles](http://r4ds.had.co.nz/tibbles.html)
* RDS [Section 11. Data Import](http://r4ds.had.co.nz/data-import.html)
* RDS [Section 12. Tidy Data](http://r4ds.had.co.nz/tidy-data.html)
* Stat545 ["Getting Data In and Out of R"](http://stat545.com/block026_file-out-in.html) 
* Stat545 ["Getting Data from the Web, Part 1"](http://stat545.com/webdata02_activity.html) 
* Stat545 ["Getting Data from the Web, Part 2"](http://stat545.com/webdata03_activity.html) 
* [Data Organization](https://kbroman.org/dataorg/) 

```{block, week08note, type='rmdnote'}
* Remember the "Data Visualization" [Cheat Sheet](https://www.rstudio.com/resources/cheatsheets/) for RStudio.
```


***
### Week 09 (MAR 19, 21)

#### Assignments Due

* DC [_Importing Data in R (Part 1)_](https://www.datacamp.com/courses/importing-data-in-r-part-1) HW
* DC [_Importing Data in R (Part 2)_](https://www.datacamp.com/courses/importing-data-in-r-part-2) HW
* ~~RDS CH027-CH28 HW~~
* Reflection #09

#### In-Class Activities

* Importing TXT files
* Importing Excel files
* Importing JSON files

#### Before Week 10

* RDS [Section 13. Relational Data](http://r4ds.had.co.nz/relational-data.html)
* RDS [Section 14. Strings](http://r4ds.had.co.nz/strings.html)
* RDS [Section 15. Factors](http://r4ds.had.co.nz/factors.html)
* RDS [Section 16. Dates and Times](http://r4ds.had.co.nz/dates-and-times.html)
* Stat545 ["When one tibble is not enough"](http://Stat545.com/block033_working-with-two-tables.html)
* Stat545 ["Cheatsheet for `dplyr` join functions"](http://Stat545.com/bit001_dplyr-cheatsheet.html)
* Stat545 ["Be the Boss of Your Factors"](http://stat545.com/block029_factors.html)
* Stat545 ["Character Data"](http://stat545.com/block028_character-data.html) 

```{block, week09note, type='rmdnote'}
* Check out the "Data Import" [Cheat Sheet](https://www.rstudio.com/resources/cheatsheets/) for RStudio.
```


***
### Week 10 (MAR 26, 28)

#### Assignments Due

* DC [_Joining Data in R with dplyr_](https://www.datacamp.com/courses/joining-data-in-r-with-dplyr) HW
* RDS CH027-CH28 HW
* RDS CH09-CH11 HW
* ~~Reflection #10~~

#### In-Class Activities

* Using `rbind` and `cbind`
* Joining files with `dplyr`
* Using `gather` and `spread`

#### Before Week 11

* RDS [Section 17: Introduction](https://r4ds.had.co.nz/program-intro.html)
* RDS [Section 18. Pipes](http://r4ds.had.co.nz/pipes.html)
* RDS [Section 19. Functions](http://r4ds.had.co.nz/functions.html)
* RDS [Section 20. Vectors](http://r4ds.had.co.nz/vectors.html)
* RDS [Section 21. Iteration](http://r4ds.had.co.nz/iteration.html)
* Stat545 ["The many flavors of R objects"](http://Stat545.com/block004_basic-r-objects.html)
* Stat545 ["Writing your own R functions Part 1"](http://stat545.com/block011_write-your-own-function-01.html)
* Stat545 ["Writing your own R functions Part 2"](http://stat545.com/block011_write-your-own-function-02.html) 

```{block, week10note, type='rmdnote'}
* Check out the "Dates and Times" and "Working with Strings" [Cheat Sheets](https://www.rstudio.com/resources/cheatsheets/) for RStudio.
```


***
### Week 11 (APR 02, 04)

#### Assignments Due

* DC [_Intermediate R_](https://www.datacamp.com/courses/intermediate-r) HW 
* ~~RDS CH13-CH16 HW~~
* Reflection #10

#### In-Class Activities

* Writing basic loops
* Writing basic functions

#### Before Week 12

* ["Clean house: clear mind. Clean data: clear findings."](https://medium.com/grinding-gears/clean-house-clear-mind-clean-data-clear-findings-e4ae2c61389c)
* ["Dealing with dirty data: useful functions for data cleaning in R"](https://medium.com/grinding-gears/dealing-with-dirty-data-useful-functions-for-data-cleaning-in-r-bcead6fd6ee6)
* ["Tricks for Cleaning Your Data in R"](https://github.com/underthecurve/r-data-cleaning-tricks/blob/master/R-datacleaning-tricks.md)

```{block, week11note, type='rmdnote'}
* Check out the "Apply Functions" [Cheat Sheet](https://www.rstudio.com/resources/cheatsheets/) for RStudio.
```


***
### Week 12 (APR 09, 11)

#### Assignments Due

* DC [_Cleaning Data in R_](https://www.datacamp.com/courses/cleaning-data-in-r) HW
* ~~RDS CH17-CH21 HW~~
* Reflection #11

#### In-Class Activities

* Exploring and cleaning data
* NA values and related functions

#### Before Week 13

* Make sure all prior work is wrapped up

```{block, week12note, type='rmdnote'}
* Now that you have assembled your data science toolbox, you will put your new skills to work on a project. This would be a good time to review the principles of reproducible research and some of your past course work. Organize your resources!
```


***
### Week 13 (APR 16, 18)

#### Assignments Due

* Project 2 plan
* Reflection #12

#### In-Class Activities

* Slides in Markdown
* Work on Project 2

#### Before Next Week

* Make progress on Project 2


***
### Week 14 (APR 25 only)

#### Assignments Due

* Project 2 progress report
* Reflection #13


#### In-Class Activities

* Work on Project 2

#### Before Next Week

* Make progress on Project 2


***
### Week 15 (APR 30 only)

#### Assignments Due

* Project 2 progress report
* Reflection #14

#### In-Class Activities

* Work on Project 2
* Work on presentation

#### Before Final Exam

* Finish report, prepare presentation


***
### Reading Day

* May 02

```{block, readingday, type='rmdnote'}
* Pause, breathe!
```


***
### Final Exam

```{block, final, type='rmdnote'}
* Our [final exam time](https://registrar.appstate.edu/sites/registrar.appstate.edu/files/asu_spring_2019_exam_schedule.pdf) is Thursday May 09 @ 2:00 pm  in our usual classroom. Project groups will give their final presentations to peers at this time and complete Reflection #15. The final report for your project is due at 9:00 am on exam day.
```
