---
title: 'Data Science Project 2'
author: 'YOUR NAMES HERE'
date: 'Updated: `r format(Sys.time(), "%A, %B %d, %Y @ %X")`'
output: html_document
---

<hr> 

1. Use dplyr functions and pipes when possible.
2. All graphs must be created using ggplot2.
3. Use informative titles and axis labels.
4. Use additional packages as needed.
5. Document any nonstandard code.

If you include any numerical values from analyses in your answers, be sure to code them with embedded r code rather than typing in the values by hand. For example, "2 + 2 = `r 2+2`" or "the current date is `r Sys.Date()`".

```{r}
# Load all packages you use here. 
# Suppress warnings and messages.
# Do not suppress the actual code.

```

#### Problem 1

The file `anthropometric.csv` contains body measurement data collected in some of Dr. Thomley's statistics classes. Students were also asked to report how tall they would like to be, if they could choose their own height. We are interested in exploring ideal height as a function of actual height, and whether gender seems to be a factor in that relationship.

* gender = student's self-identified gender
* height = measured height (inches)
* armspan = measured fingertip to fingertip armspan (inches)
* forearm = measured elbow to fingertip forearm length (inches) 
* hand = measured wrist to fingertip length (inches)
* leg = measured knee (back) to heel height (inches)
* foot = measured heel to toe length (inches)
* ideal = height the student would like to be (inches)
* semester = semester in which the data was collected

Note: There are only a few points with a gender other than male or female, so they will be excluded from the analyses due to insufficient sample size for linear modeling. You may opt to remove additional points you believe to be outliers, but you must provide justification for your choices. If you do not remove any additional points, explain why you chose not to.

A) Create a scatterplot of height (x) versus ideal (y). Include:

* fitted linear models by gender (males and females only)
* model equations and R^2^ values shown on the plot
* colors other than the ggplot2 defaults

B) Create scatterplots of height (x) versus ideal (y). Include:

* faceting so the female plot is shown above the male plot
* a line on each gender's scatterplot to indicate ideal = height
* colored points to show where ideal height is >, <, or = height
* a vertical line on each plot to show that gender's mean height
* labels to indicate that the vertical lines are sample means
* colors other than the ggplot2 defaults

C) Show the loess-smoothed models for height (x) versus ideal height (y) by gender on a single plot, without any data points.

JUSTIFICATION FOR REMOVAL/NON-REMOVAL OF POINTS:

QUESTION 1: Do people generally seem to be happy with their actual heights? Explain.

QUESTION 2: Do males and females seem to feel differently about ideal height? Explain.


#### Problem 2

The Excel file `powerball.xlsx` contains data on the winning numbers drawn and Jackpot amounts for the [Powerball Lottery](https://www.powerball.com/games/powerball) for the past several years. The current instructions for how to play Powerball, as published on the lottery's website, are as follows.

* Powerball® costs $2 per play. 
* Select five numbers from 1 to 69 for the white balls; then select one number from 1 to 26 for the red Powerball.
* Choose your numbers on a play slip or let the lottery terminal randomly pick your numbers.
* Jackpots start at $40 million and grow from there!
* Players win a prize by matching one of the 9 Ways to Win.

Players have always selected five white balls and one red ball. However, the Powerball lottery has had different rulesets over time with respect to how many white and red balls there are for players to choose from, which affects the chances of winning the various prizes. Data about the number of balls is also included in `powerball.xlsx`. In theory, drawings are random and independent, so all white balls are equally likely to be chosen. The same is true of all red balls. The Jackpot increases in value until someone wins and then it resets to its minimum value. 

A) Use the `readxl` package to import all of the worksheets in `powerball.xls`. 

B) Create a data frame/tibble containing the following variables.

* startdate (date) -- starting date for a given ruleset
* enddate (date) -- the ending date for a given ruleset
* whiteballs (numeric) -- number of white balls to choose from
* redballs (numeric) -- number of red balls to choose from
* combinations (numeric) -- number of unique ticket combinations 

C) Create a data frame/tibble containing the following variables.

* drawdate (date) -- date the drawing took place
* drawday (factor) -- day of the week the drawing took place
* white1 (numeric) -- first white ball number
* white2 (numeric) -- second white ball number
* white3 (numeric) -- third white ball number
* white4 (numeric) -- fourth white ball number
* white5 (numeric) -- fifth white ball number
* powerball (numeric) -- powerball (red) ball number
* redballs (numeric) -- number of red balls to choose from
* whiteballs (numeric) -- number of white balls to choose from
* jackpot (numeric) -- total dollar value of the jackpot
* jackpot2018 (numeric) -- jackpot value in 2018 dollars

To adjust a dollar value for inflation, we multiply by the inflation factor, which is derived from the consumer price index. For example, suppose I had \$100 in 2016. Inflation from 2016 to 2017 is 2.11%. Therefore, \$100 in 2016 dollars is the equivalent of \$100 &times; 1.0211 = \$102.11 in 2017 dollars. Similarly, \$100 in 2015 dollars is 100 &times; 1.0207 &times; 1.0211 = \$104.22 in 2017 dollars, since the 2015 to 2016 inflation rate is 2.07%. So, \$100 in the past is actually worth more, relatively speaking, than \$100 now. Inflation data is included in the Excel file.

D) Create a grouped barplot that shows the number of red and white balls for each ruleset. 

E) Create a barplot that shows the number of unique ticket combinations for each ruleset. Set the widths of the bars so they reflect the relative proportion of time each ruleset was in use in our dataset. 

F) Create a visualization to show the realtive frequencies of occurrance of each red ball number. Be sure to account in some way for the fact that the number of red balls to choose from has changed over time.

G) Create a visualization to show the relative frequencies of occurrance of each white ball number. You will need to pool all the white ball data since the white numbers are all drown from the same bin. Be sure to account for the fact that the number of white balls to choose from has changed over time.

H) Create a time series plot that shows the value of the Jackpot over time, both in original dollars and adjusted dollars. Indicate in some way the point(s) in time at which the minimum Jackpot value increased.

QUESTION 1: Does it appear that the white numbers are equally likely to occur? Explain.

QUESTION 2: Does it appear that the red numbers are equally likely to occur? Explain.

QUESTION 3: Are Jackpots larger now than in the past?


#### Problem 3

Create one additional visualization using the anthropometric data and one additional visualization using the powerball data. Choose something that interests you&mdash;perhaps a plot type we have not used in either project. They should not be too similar to the plots you have already created above. You will present these to the class during the final exam period as well as including them in this document.

<hr>

DONE!!!

